### ISSUE TITLE
Samodejno preverjanje formatiranja kode

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/nadlogar#15]
V GitHub action, definiran v `.github/workflows/django.yml` bi bilo (verjetno za izvedenimi testi?) treba dodati še preverjanje formatiranja glede `black` s privzetimi nastavitvami.

**Comment by matijapretnar** [comment]
Prav tako je treba Github action popraviti tako, da bo zares pognal teste.

**Comment by jureslak** [comment]
Problem s testi je njihov discovery (https://docs.djangoproject.com/en/3.1/topics/testing/overview/#running-tests). Če bi se premaknil, tako da je cwd `nadlogar`, potem `python manage.py test` deluje. Lahko se doda `-s` flag (https://docs.python.org/3/library/unittest.html#unittest-test-discovery), ali pa (po mojem bolje), požene zadevo iz django roota.
