### ISSUE TITLE
Dokumentacija generičnih delov kode

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/nadlogar#16]
Programska koda je sedaj napisana tako, da je za dodajanje novega tipa naloge treba dodati le en model za parametre skupaj s funkcijo za generiranje, iz tega pa se potem avtomatično naredijo obrazci, povezave z besedili, … Gre za en kup Python čarovnije, ki bi jo bilo dobro dokumentirati v kodi.

Dokumentacija naj:

- [ ] bo kompatibilna s Sphinxom
- [x] čimveč stvari je napisanih v docstringih
- [x] govori o tem, kaj je namen funkcij
- [x] o delovanju funkcij govori samo, če je to treba posebej razložiti
- [x] ima pike na koncu docstringov

**Comment by matijapretnar** [comment]
Dokumentacija naj:

- [ ] bo kompatibilna s Sphinxom
- [ ] čimveč stvari je napisanih v docstringih
- [ ] govori o tem, kaj je namen funkcij
- [ ] o delovanju funkcij govori samo, če je to treba posebej razložiti
- [ ] ima pike na koncu docstringov

**Comment by nikerzetic** [comment]
V katerem jeziku bomo pisali dokumentacijo; v slovenščini (s šumniki ali brez) ali angleščini?

**Comment by matijapretnar** [comment]
Ker so generični deli v angleščini, predlagam, da so tudi komentarji v angleščini. Edini del, kjer bi pisal slovensko tako kodo kot komentarje, so konkretni generatorji (kakršni so na dnu `problems/models.py`, čeprav bodo verjetno v kratkem šli v svoje datoteke).

**Comment by jureslak** [comment]
Se strinjam, ko pa so v slovenščini, so pa lahko normalno s šumniki, ni razloga zakaj ne bi delalo.

**Comment by matijapretnar** [comment]
Sem po nasvetu @katjabercic sklenil, da tu jaz prevzamem pobudo, pa da so ostali reviewerji končnega pull requesta #75, saj se bo tako najbolj jasno videlo, kaj ni jasno. Predlagam, da se vsa vprašanja glede kode vodi tam.
