### ISSUE TITLE
Prenos PDFja z nadlogami

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/nadlogar#18]
Obstoječi HTML predogled je treba polepšati, zraven pa ponuditi še prenos PDFja. Razmisliti bi bilo treba o tem, da za PDF obstaja več možnih predlog.

**Comment by matijapretnar** [comment]
Morda bi za generiranje PDFja uporabljali https://github.com/cs50/render50

**Comment by matejm** [comment]
Glede na to, da se bomo mučili s HTML predogledom, se mi ne zdi smiselno, da potem PDFje generiramo z Latex-om.

Pri HTML predogledu bodo težave povsod, kjer uporabljamo TikZ (npr. risanje grafa polinoma, racionalne funkcije, ...), saj Mathjax tega ne zna. Lahko si pomagamo s [TikZJax](https://github.com/kisonecat/tikzjax)-om (nimam pojma v kakšni meri to zares deluje), vendar moramo potem tudi vse PDFje generirati v brskalniku.

**Comment by jureslak** [comment]
Alternativno, lahko razmišljamo tudi o tem, da generiramo samo PDF, ki se ga potem pokaže na strani s pomočjo embedded PDF viewerja. V vsakem primeru je lepo, da imamo samo en primaren format za output. 

Vecina uciteljev sicer naloge sestavlja v Wordu, tako da bi lahko tudi ponudili download posamezne naloge kot `.png` slike (ja, vem), tako da je potem to enostavno zložiti skupaj in dodati okrog poljubno besedilo.

**Comment by matijapretnar** [comment]
Kakšne variante pa imamo za generiranje PDFjev, glede na to, da želimo podpirati matematične simbole? Lahko uporabimo LaTeX na backendu ali MathJax oz. KaTeX na frontendu. A je še kakšna možnost?

**Comment by jureslak** [comment]
Sploh če hočemo podpirati grafe funkcij in kaksne bolj komplicirane strukture, da je edina extensible možnost LaTeX backend. 

Sicer pa bi lahko uporabljali marsikaj drugega (recimo `sphinx`), ampak na koncu, ce je zadeva backend, ima skoraj gotovo depenedency na `texlive`, ce pa je frontend, pa na `mathjax` (ali `katex`). Še vedno pa podpiram, da če imamo "primarni" pogled na frontend, potem se lahko PDF naredi tako, da se sprinta primeren frame, tako da user res dobi to kar vidi, sicer moras vedno usklajevati več zadev.

Drugih dejanskih paketov za render matematike pa ne poznam.

**Comment by matijapretnar** [comment]
Koliko se pa lahko zanašamo na generiranje PDFjev v brskalnikih? Si predstavljam, da obstajajo tudi JS knjižnice za risanje grafov, samo pojma nimam, kako na koncu to izpade v PDFju. Potem so tu še prelomi strani in podobne stvari, ki jih v HTMLju težje dosežemo.

Tako da se tudi meni zdi LaTeX najbolj sigurna varianta, čeprav se mi ne zdi narobe pokazati tudi kakšen MathJaX preview (npr. samo za eno nalogo naenkrat ali kaj takega). @matejm - a ste vi izrazili neke zadržke glede uporabe LaTeXa na backendu? A ste imeli v mislih strežniške kapacitete ali kaj drugega? Ker načeloma se uporabnikom ne bo treba toliko ukvarjati s pisanjem TeXa, ker bodo obstajale že pripravljene predloge.

**Comment by matijapretnar** [comment]
Ko sem komentiral #40 sem ugotovil, da bo na veliko koncih koristen HTML predogled besedila. Če za trenutek odmislimo grafe, a bo res taka huda razlika med MathJaX izpisom fragmentov na strani in z LaTeXom generiranim PDF izpisom vseh nalog?
