### ISSUE TITLE
Dodatni tipi nalog - eksponentna funkcija

### ISSUE THREAD

**Issue by matejm** [ul-fmf/nadlogar#27]
Razbijam issue #14. Dodati je treba naloge iz poglavja o eksponentni funkciji:

- [ ] [Naloga iz risanja grafov](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/eksponentna_funkcija.py#L34)
- [x] [Naloga za reševanje eksponentne enačbe](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/eksponentna_funkcija.py#L119)
- [x] [Naloga enačbe, kjer imata potenci različni osnovi](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/eksponentna_funkcija.py#L185)

Vse naloge morajo pri implementaciji slediti dokumentaciji za pisanje generatorjev (ki je še v nastanjanju, glej #24).

**Comment by MightyOwler** [comment]
> Razbijam issue #14. Dodati je treba naloge iz poglavja o eksponentni funkciji:
> 
> * [ ]  [Naloga iz risanja grafov](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/eksponentna_funkcija.py#L34)
> * [x]  [Naloga za reševanje eksponentne enačbe](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/eksponentna_funkcija.py#L119)
> * [x]  [Naloga enačbe, kjer imata potenci različni osnovi](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/eksponentna_funkcija.py#L185)
> 
> Vse naloge morajo pri implementaciji slediti dokumentaciji za pisanje generatorjev (ki je še v nastanjanju, glej #24).

**Comment by matijapretnar** [comment]
Z izjemo #90 vse rešeno.
