### ISSUE TITLE
Funkcionalnost spletnega vmesnika

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/nadlogar#3]
Določiti je treba, kako storitev deluje: kaj je na voljo, kakšen je videti vmesnik, katere zmožnosti so na voljo in podobno.

Se priporočam za kakršnekoli ideje v kakršnikoli obliki (sken, tekst, link na dobro narejene strani ali kaj drugega).

**Comment by barbara7777** [comment]
![IMG_20191214_094700-01](https://user-images.githubusercontent.com/42250908/70846299-3bf3a500-1e58-11ea-8615-217ec3cb5798.jpeg)

Moj predlog je, da bi na osnovni strani naredili pregled po kategorijah oziroma temah za naloge. Način, ki ga ima [astra](https://astra.si/),  se mi zdi (razen reklam) pregleden.
Način za izbiranje in dodajanje nalog h končnemu učnemu listu, bi lahko bil podoben spletni trgovini. Na enak način bi lahko dodajali naloge na učni list kot izdelke v košarico. Na koncu pa bi bila možnost za urejanje sestavljenega učnega lista.

**Comment by MatejOcvirk** [comment]
Storitev za ustvrajnanje testov ima založba Rokus Klett, pod imenom "klikTEST". Gre se za poučevanje razrednega pouka na osnovnošolskem nivoju, naloge so vnaprej določene in izbrane iz njihovih učbenikov, spletna storitev omogoča ustvarjanje preverjanj v Word dokumentih (.doc).

Kolikor vem, se osredotočajo na učne načrte podane s strani države in po njih sortirajo možne naloge. To se mi zdi primerno za učitelje na osnovnih in srednjih šolah, kjer je potrebno slediti učnim načrtom. Na primer, za učitelje bi bilo enostavneje zbirati naloge v posameznem sklopu, ki ga opisuje učni načrt, kot pa iskanje posameznih primerov, ki bi zadostili učnim ciljem. Še link na primer učnega načrta za matematiko v OŠ: [LINK](https://www.gov.si/assets/ministrstva/MIZS/Dokumenti/Osnovna-sola/Ucni-nacrti/obvezni/UN_matematika.pdf)

Dostopa do storitve nimam (je plačljivo), bom pa v roku naslednjih nekaj dni dobil slike, kako zadeva zgleda.

**Comment by Tejchy85** [comment]
Izgled strani, ki jo je predstavila @barbara7777  mi je všeč, bi pa predlagala da bi učitelj naprej izbral ali gre za osnovno šolo ali srednjo šolo (mogoče bi tukaj bilo potrebno deliti še na gimnazijo in poklicno srednjo šolo), nato razred, in nato se ponudi vsa poglavja iz tega letnika (tu se strinjam z @MatejOcvirk , da sledimo učnim načrtom).

**Comment by CvrtilaV** [comment]
Jaz bi predlagal, da bi samo sestavljanje testov lahko naredili podobno kot ustvarjanje strani na [moodle-u](https://sandbox.moodledemo.net/). Začneš s praznim listom, ki je lahko razdeljen na več razdelkov, nato pa lahko v vsakega dodaš naloge, dodatna navodila, pojasnila ipd.
![Screenshot_2019-12-16 Course Test](https://user-images.githubusercontent.com/22882698/70941575-0bc12780-204d-11ea-863c-1178c0645118.png)
![Screenshot_2019-12-16 Course Test(2)](https://user-images.githubusercontent.com/22882698/70941330-7de53c80-204c-11ea-8977-0909aac70624.png)
Vsakič, ko bi kaj hotel dodati, bi dobil okno z opcijami oz. z prikazom tipov nalog. Tu bi verjetno rabili dodati možnosti filtriranja glede na težavnost ipd. ter bolj pregleden način prikazovanja vsega.

**Comment by CvrtilaV** [comment]
Na zadnjem sestanku smo se dogovorili za terminologijo.

![IMG_20191218_151405](https://user-images.githubusercontent.com/22882698/71093413-6a031d00-21a9-11ea-8b57-2675e6fed65b.jpg)

**Comment by matijapretnar** [comment]
@CvrtilaV hvala! Za terminologijo sem naredil nov issue #4.

@Tejchy85 in @MatejOcvirk sta predlagala, da k pogovoru povabimo tudi učitelje in študente pedagoške matematike. Predlagam, da to naredimo na naslednjem srečanju v začetku januarja.

Pogovarjali smo se tudi o: formatu (LaTeX, HTML, …), kaj omogočamo anonimnim uporabnikom, … Če ima kdo voljo, naj prosim odpre ustrezen issue.

**Comment by matijapretnar** [comment]
Ker je čas, da se nehamo dogovarjati in začnemo delati, bom ta issue zaprl. Zdaj imamo približno sliko, česa si želimo, zato bi naredil nek prototip in učitelje povabil takrat, ko bomo lahko že kaj pokazali.
