### ISSUE TITLE
Dodatni tipi nalog - množice

### ISSUE THREAD

**Issue by matejm** [ul-fmf/nadlogar#33]
Razbijam issue #14. Dodati je treba naloge iz množic:

- [ ] [Naloga za izpis posameznih elementov množice iz podanega predpisa](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/mnozice.py#L31)
- [ ] [Naloga za zapis potenčne množice](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/mnozice.py#L98)
- [ ] [Naloga za zapis unije, presek, razlike in kartezičnega produkta množic](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/mnozice.py#L143)
- [ ] [Naloga za izračun komplementa, unije in razlike množic ter izpis elementov izpeljane množice pri podani univerzalni množici](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/mnozice.py#L199)

Vse naloge morajo pri implementaciji slediti dokumentaciji za pisanje generatorjev (ki je še v nastanjanju, glej #24).

**Comment by matijapretnar** [comment]
Closed by #52
