### ISSUE TITLE
Dodatni tipi nalog - odvodi

### ISSUE THREAD

**Issue by matejm** [ul-fmf/nadlogar#35]
Razbijam issue #14. Dodati je treba naloge iz sklopa odvodi:

- [ ] [Naloga za izračun kota med dvema premicama](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L177)
- [ ] [Naloga za odvajanje kompozituma 2 izbranih elementarnih funkcij iz podanega seznama](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L241)
- [ ] [Naloga za odvajanje sestavljene funkcije iz podanega seznama elementarnih funkcij](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L330)
- [ ] [Naloga za izačun tangente na graf v določeni točki](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L423)
- [ ] [Naloga za izračun kota med grafoma dveh funkcij (kvadratnih, logaritmov ali eksponentnih)](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L519) 

Vse naloge morajo pri implementaciji slediti dokumentaciji za pisanje generatorjev (ki je še v nastanjanju, glej #24).

**Comment by MightyOwler** [comment]
> Razbijam issue #14. Dodati je treba naloge iz sklopa odvodi:
> 
> * [x]  [Naloga za izračun kota med dvema premicama](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L177)
> * [x]  [Naloga za odvajanje kompozituma 2 izbranih elementarnih funkcij iz podanega seznama](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L241)
> * [x]  [Naloga za odvajanje sestavljene funkcije iz podanega seznama elementarnih funkcij](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L330)
> * [x]  [Naloga za izačun tangente na graf v določeni točki](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L423)
> * [x]  [Naloga za izračun kota med grafoma dveh funkcij (kvadratnih, logaritmov ali eksponentnih)](https://github.com/ursa16180/generiranje-nalog/blob/2a7c84f9b4842b7c63136cd2e6b8a68000394576/odvodi.py#L519)
> 
> Vse naloge morajo pri implementaciji slediti dokumentaciji za pisanje generatorjev (ki je še v nastanjanju, glej #24).
