### ISSUE TITLE
Obrazec za dodajanje instanc ProblemText

### ISSUE THREAD

**Issue by smeznar** [ul-fmf/nadlogar#40]
Potrebno se je zmeniti, kako bo izgledal obrazec za dodajanje instanc ProblemText (struktura besedila in odgovora problema) ter kje se bo na strani nahajal. Za tem je zmenjeno potrebno implementirati.

- [x] Dogovor izgleda in mesta na strani.
- [x] Implementacija.

**Comment by matijapretnar** [comment]
Zdi se mi, da bi za lastno uporabo lahko besedila dodajal vsak, npr. da malenkostno spremeni kakšno besedilno nalogo ali kaj takega. Zaenkrat bi stvar dal na levo pod kvize in razrede, samo mogoče ne bi naštel vseh, temveč bi samo dal link. Nato pa so na tisti strani besedila razvrščena po tipih nalog (ki bodo kasneje kategorizirane). Lepo bi bilo, če bi pri vsaki nalogi vsa besedila izpisali z istimi parametri, da se vidi razlika.

Bi pa verjetno želeli imeti tudi neko "uradno" zbirko besedil. Ena možnost je, da je nek boolean flag `javno` in to delamo ročno ter po vrsti pokažemo vse take. Druga možnost je, da vsak učitelj besedila označi kot javna, pa se pokažejo vsem ostalim, ampak urejena padajoče po številu uporab, da bodo boljša splavala na vrh.

**Comment by matijapretnar** [comment]
Predlagam, da se obrazec za dodajanje novih besedil nahaja kar na strani, kjer se izbira besedilo za določeno nalogo, saj je tam najbolj relevanten. Torej, ko izberemo parametre, bi se lahko zgenerirali neki vzorčni podatki, potem pa se prikažejo možna besedila (kar izpisana z vstavljenimi podatki), uporabnik pa med njimi izbere eno ali napiše svojo predlogo.
