### ISSUE TITLE
Križec ne zapre obrazca za urejanje 

### ISSUE THREAD

**Issue by barbara7777** [ul-fmf/nadlogar#42]
V `form.html` imamo v `class="modal is-active"` akcijo, ki bi naj ta obrazec za urejanje zaprl. Ta pošlje uporabnika na stran, iz katere je prišel (na naslov `request.META.HTTP_REFERER`). Nekateri obrazci imajo več korakov, zato se to zapiranje zacikla, če poskusimo obrazec zapreti na katerem poznejšem koraku.

**Comment by matijapretnar** [comment]
Ja, tako, kot so trenutno narejeni obrazci, je bolj hack, in tu se pokaže, zakaj. Boljša rešitev bi bila obrazce pokazati modalno, torej da klik ne odpelje na novo stran z obrazcem, temveč da se obrazec naloži z JavaScriptom. Imamo koga, ki je malo bolj domač z JavaScriptom? Če se da, bi uporabljal osnovni in na roke napisani JavaScript, ne pa še enega kupa knjižnic.
