### ISSUE TITLE
Več identičnih podnalog

### ISSUE THREAD

**Issue by MightyOwler** [ul-fmf/nadlogar#81]
Trenutno se lahko zgodi, da so nekatere podnaloge med seboj identične. Sklepam, da je to posledica uporabe *sympy.simplify()*, mogoče pa bi bilo, da se problem pojavi že pri generiranju podnalog.

**Comment by matijapretnar** [comment]
Aha, dobra opazka. To lahko rešimo v splošnem, da takrat, ko zgeneriramo več podatkov, poskrbimo, da so med sabo različni.
