### ISSUE TITLE
Pomanjkanje splošno uporabnih generatorjev

### ISSUE THREAD

**Issue by MightyOwler** [ul-fmf/nadlogar#83]
Opazil sem, da nekatere naloge potrebujejo generatorje polinomov, kvadratnih funkcij splošne in ničelne oblike... Pomembne generatorje je treba identificirati in jih napisati v neko datoteko s pomožnimi funkcijami.

V [Uršinem projektu](https://github.com/ursa16180/generiranje-nalog) je veliko teh funkcij že napisanih in niso ekstremno zahtevne.

Edit: V živo smo se zmenili, da zaenkrat ne bomo delali posamezne datoteke za take funkcije, ker bi to spremenilo strukturo projekta. Bomo pa morda kdaj v prihodnosti.

**Comment by matijapretnar** [comment]
Zaenkrat zapiram issue, lahko se ga odpre ob priliki, ko posamezne funkcije ne bodo več dovolj.
