### ISSUE TITLE
Pojavi se "\r\n" namesto"\n"

### ISSUE THREAD

**Issue by NotNotLuka** [ul-fmf/nadlogar#89]
Če ima privzeto besedilo tipa naloge več vrstic se pri primerjanju ali je uporabnik spremenil besedilo pojavi "\r\n" namesto "\n" in posledično uporabniku sporoči napako.

**Comment by matijapretnar** [comment]
Kot smo zadnjič ugotovili, se `\r\n` pojavi, ker ga pošlje spletni brskalnik. Nad tem, kaj brskalnik pošlje, nimamo nadzora. Malo nadzora imamo nad privzetim besedilom, saj lahko že Git poskrbi, da so vsa ločila vrstic konsistentna. Ampak najbolj enostavno je, da ob primerjavi besedil obe strani normaliziramo. Zato v Djangu že obstaja `from django.utils.text import normalize_newlines`.
